# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  codegeneratorservice:
    image: marathaa/codegenerationservice:v1  
    container_name: codegeneratorservice  
    ports:
      - "8080:80" 
      - "8081:443"  
    networks:
      - backendnet
    depends_on:
      - storageservice 

    
  storageservice:
    image: marathaa/storageservice:v1  
    container_name: storageservice  
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backendnet
    depends_on:
      - sqldbservice      



  sqldbservice:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    container_name: sqldbservice
    restart: always   
    environment:
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=Abcd@123456789 
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    networks:
      - backendnet


networks:
  backendnet:
    driver: bridge