# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  storageservice:
    image: storageservice
    build:
      context: .
      dockerfile: storageservice/Dockerfile
    ports:
      - 5054:5054
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
